{% set name = "wagtail-ab-testing" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9e65629cd1d537b7657630de8588825cd306eafbd92af09493b28b6d35b3ede0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wagtail >=5.2
    - user-agents >=2.2,<2.3
    - numpy >=1.19.4,<2
    - scipy >=1.5.4,<2

test:
  imports:
    - wagtail_ab_testing
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A/B Testing for Wagtail
  home: https://github.com/wagtail-nest/wagtail-ab-testing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
