{% set name = "wagtail-ab-testing" %}
{% set version = "0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 56a3143a8e426eac1c76b9c517cdda1f40c45e37dfff6e836216fb3d7b79cf86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - wagtail >=5.2
    - user-agents >=2.2,<2.3
    - numpy >=1.19.4,<2
    - scipy >=1.5.4,<2

test:
  imports:
    - wagtail_ab_testing
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A/B Testing for Wagtail
  home: https://github.com/wagtail-nest/wagtail-ab-testing
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
